[package]
name = "lexi"
version = "0.1.0"
description = "An assistant for Roblox Word Bomb game"
authors = ["KingCharlesVII"]
edition = "2021"

[lib]
name = "lexi_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-shell = { version = "2.2.0", features = [] }
tauri-plugin-dialog = { version = "2.2.0", features = [] }
tauri-plugin-fs = { version = "2.2.0" }
tauri-plugin-process = { version = "2.2.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8.0"
inputbot = "0.6.0"
windows = { version = "0.61.1", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }

[features]
default = []

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
